Description: >
    This template deploys the entire Hakken AM stack to an environment.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Default: dev 
    AllowedValues: 
      - dev
      - qa
      - prod
    Type: String


Resources:
  AMScannerStack:
    Type: AWS::CloudFormation::Stack 
    Properties:
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      TemplateURL: !Sub 'https://s3.amazonaws.com/linkai-infra/templates/am-external.yaml'
      TimeoutInMinutes: '30'
  